### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by quhtani** [JackDougherty/fusion-point-polygon-list#29]
I have the same IPA key. I used it for different files. It didn't work with this code but it worked with the other one. May I know the problem plz?
both files are on these links.
this one is not working -> http://quhtani.com/0A/index.html
this one is working -> http://quhtani.com/0A/index2.html

**Comment by JackDougherty** [comment]
Sorry, but I do not support this Google Fusion template. Post questions to the Google Group on Derek’s page
http://derekeder.com/searchable_map_template/
